//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GameStop
    {
        public int Juego { get; set; }
        public string Nombre { get; set; }
        public string Categoria { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Plataforma { get; set; }
        public string Stock { get; set; }
    }
}
